### ISSUE TITLE
编译所需opencv版本是什么？

### ISSUE THREAD

**Issue by OrangeJuice3211** [HorizonRDK/mono3d_indoor_detection#8]
编译报错，‘CV_YUV2BGR_NV12’ was not declared in this scope，所用旭日X3开发板中opencv版本为 4.8.0.76

**Comment by zhukao** [comment]
需要使用3.4.5版本的opencv，X3开发板系统自带的就是这个版本，你这边是有重新安装或者升级opencv吗？
开发板上执行`ls /usr/include/opencv*`命令看下，`CV_YUV2BGR_NV12`在`/usr/include/opencv2/imgproc/types_c.h`这个文件中。
